routes/web.php
    Route::patch("/patients/{patient}/stationary/{stationary}/cellular_examination", "StationaryController@cellular_examination")->name("patients.stationary.cellular_examination");
    Route::patch("/patients/{patient}/stationary/{stationary}/expert_advice", "StationaryController@expert_advice")->name("patients.stationary.expert_advice");
    Route::patch("/patients/{patient}/stationary/{stationary}/for_analysis", "StationaryController@for_analysis")->name("patients.stationary.for_analysis");
    Route::patch("/patients/{patient}/stationary/{stationary}/surgery_justification", "StationaryController@surgery_justification")->name("patients.stationary.surgery_justification");
    Route::patch("/patients/{patient}/stationary/{stationary}/surgery_protocol", "StationaryController@surgery_protocol")->name("patients.stationary.surgery_protocol");
    Route::patch("/patients/{patient}/stationary/{stationary}/surgery_description", "StationaryController@surgery_description")->name("patients.stationary.surgery_description");
    Route::patch("/patients/{patient}/stationary/{stationary}/disease_course", "StationaryController@disease_course")->name("patients.stationary.disease_course");
    Route::patch("/patients/{patient}/stationary/{stationary}/resuscitation_department", "StationaryController@resuscitation_department")->name("patients.stationary.resuscitation_department");
    Route::patch("/patients/{patient}/stationary/{stationary}/epicrisis", "StationaryController@epicrisis")->name("patients.stationary.epicrisis");
    Route::patch("/patients/{patient}/stationary/{stationary}/pathological_anatomical", "StationaryController@pathological_anatomical")->name("patients.stationary.pathological_anatomical");
    Route::patch("/patients/{patient}/stationary/{stationary}/treatment_evaluation", "StationaryController@treatment_evaluation")->name("patients.stationary.treatment_evaluation");
    Route::patch("/patients/{patient}/stationary/{stationary}/special_note", "StationaryController@special_note")->name("patients.stationary.special_note");
    Route::patch("/patients/{patient}/stationary/{stationary}/special_note", "StationaryController@special_note")->name("patients.stationary.special_note");

    Route::resource("reception_queues", "Api\QueueController"); // all real, for testing only create-store
    # api testing users
    Route::get('users/{user}/patients/{patient}', 'Api\UserController@patient');
    Route::get('users/{user}/patients', 'Api\UserController@patients');

    Route::resource('calendar', 'Calendar\CalendarController');
    Route::post('calendar/find', 'Calendar\CalendarController@find')->name('calendarfind');
    Route::post('calendar/storeCalendar', 'Calendar\CalendarController@store')->name('calendarstore');
    Route::resource('users', 'UsersController');
    Route::post('users/store_file', 'UsersController@store_file')->name('users.store_file');
    Route::get('users/change/password', 'UsersController@changePssword')->name('users.changeUserPassword');
    Route::post('users/update/password', 'UsersController@updatePssword')->name('users.updateUserPassword');

    Route::group(['prefix' => 'dtssp', 'as' => 'dtssp.'], function () {
        # test-group for server-side dataTables processing
        Route::get('/users', 'UsersController@dtIndex')->name('users.index');
        Route::get('/users_processing', 'UsersController@dtIndexProcessing')->name('users.processing');
    });


    Route::resource('cashbox', 'CashboxController', ['names' => 'cashbox']);
    Route::group(["namespace" => "Orders"], function () {

        Route::resource('cashbox/cashboxFirst/orderoutput', 'OrderOutputForCahhboxFirstController', ['as' => 'cashbox.cashboxFirst']);
        Route::resource('cashbox/cashboxSecond/orderoutput', 'OrderOutputForCahhboxSecondController', ['as' => 'cashbox.cashboxSecond']);
        Route::resource('cashbox/cashboxSecond/orderoutput', 'OrderOutputForCahhboxSecondController', ['as' => 'cashbox.cashboxSecond']);
        Route::resource('cashbox/cashboxThirth/orderoutput', 'OrderOutputForCahhboxThirthController', ['as' => 'cashbox.cashboxThirth']);
        Route::resource('cashbox/cashboxFour/orderoutput', 'OrderOutputForCahhboxFourthController', ['as' => 'cashbox.cashboxFour']);

        Route::resource('/cashbox/cashboxFirst/orderinput', 'OrderInputForCahhboxFirstController', ['as' => 'cashbox.cashboxFirst']);
        Route::resource('/cashbox/cashboxSecond/orderinput', 'OrderInputForCahhboxSecondController', ['as' => 'cashbox.cashboxSecond']);
        Route::resource('/cashbox/cashboxThirth/orderinput', 'OrderInputForCahhboxThirtController', ['as' => 'cashbox.cashboxThirth']);
        Route::resource('/cashbox/cashboxFour/orderinput', 'OrderInputForCahhboxFourthController', ['as' => 'cashbox.cashboxFour']);
    });
});
Route::group(['prefix' => 'otherSamples', "namespace" => "OtherSamples", "as" => "otherSamples."], function () {

    Route::resource("parentOtherSamples", "OtherSamplesController");
    Route::resource(
        'ptc',
        'ProcurementTechnicalCharacteristicsController',
        ["except" => ["delete"], 'parameters' => ['procurement_technical_characteristics' => 'ptc']]
    );
    Route::resource(
        "accounting-for-research",
        'AccountingForResearchController',
        ["except" => ["delete"]]
    );

    Route::resource(
        "departments.work-time-bulletins",
        "DepartmentWorkTimeBulletinController"
    );

    Route::resource(
        "users.work-time-bulletins",
        "UserWorkTimeBulletinController"
    );
});


Route::group(['prefix' => 'catalogs', "namespace" => "Catalogs", "as" => "catalogs."], function () {
    Route::get('/harmfuls.json', 'HarmfulController@harmfuls_json');
    Route::get('/medicines.json', 'MedicineListController@medicines_json');
    Route::get('/diseases.json', 'DiseaseListController@diseases_json');
    Route::get('/treatments.json', 'TreatmentListController@treatments_json');
    Route::get('/tumor_treatments.json', 'TumorTreatmentListController@tumor_treatments_json');
    Route::get('/clinics.json', 'ClinicController@clinics_json')->name('clinics_json');
    Route::get('/surgeries.json', 'SurgeryListController@surgeries_json');
    Route::get('/anesthesias.json', 'AnesthesiaListController@anesthesias_json');
    Route::get('/departments.json', 'DepartmentListController@departments_json');
    Route::get('/departments_full.json', 'DepartmentListController@departments_full_json')->name('departments_full');

    Route::get('/chambers.json', 'ChamberListController@chambers_json');
    Route::get('/beds.json', 'BedListController@beds_json');
    Route::get('/lab_service.json', 'LabServiceListController@lab_json');

    Route::get('/samples', 'SampleController@index');
    Route::get('/samples2', 'SampleController@index2');
    Route::get('/samples/target/{target}', 'SampleController@groupByTarget');
    Route::get('/samples/target2/{target}', 'SampleController@groupByTarget2');

    // Route::resource('departments', 'DepartmentListController'); // admin CRUD
    Route::get('/measurement_units.json', 'MeasurementUnitController@measurement_units_json');
    Route::get('/services_full.json/{filterBy?}{needle?}', 'ServiceListController@services_full_json')->name('services_full');

    Route::get('/paid_services_k1.json', 'ServiceListController@paid_services_k1_json')->name('paid_services_k1_json');
    Route::get('/paid_services_k2.json', 'ServiceListController@paid_services_k2_json')->name('paid_services_k2_json');
    Route::get('/paid_services.json', 'ServiceListController@paid_services_json')->name('paid_services_json');
    Route::get('/state_ordered_services.json', 'ServiceListController@state_ordered_services_json')->name('state_ordered_services_json');
    Route::get('/payment_types.json', 'PaymentTypeListController@payment_types_json')->name('payment_types_json');
    Route::get('/payment_types_hy.json', 'PaymentTypeListController@payment_types_hy_json')->name('payment_types_hy_json');

    Route::get('/social_packages.json', 'SocialPackageController@social_packages_json');

    Route::get('/living_place_list.json', 'LivingPlaceListCotroller@living_place_list_json');
    Route::get('/social_living_condition_list.json', 'SocialLivingConditionListCotroller@social_living_condition_list_json');
    Route::get('/working_feature_list.json', 'WorkingFeatureListCotroller@working_feature_list_json');
    Route::get('/education_list.json', 'EducationListCotroller@education_list_json');
    Route::get('/marital_status_list.json', 'MaritalStatusListCotroller@marital_status_list_json');

    Route::get('/application_purpose_list.json', 'ApplicationPurposeListController@application_purpose_list_json');
    Route::get('/registration_option_list.json', 'RegistrationOptionListController@registration_option_list_json');
    Route::get('/researches_lists.json', 'ResearchesListController@researches_lists_json');
    Route::get('/histological_structure_lists.json', 'HistologicalStructureListController@histological_structure_lists_json');
    Route::get('/not_carrying_out_treatment_reason_lists.json', 'NotCarryingOutTreatmentReasonListController@not_carrying_out_treatment_reason_lists_json');
    Route::get('/treatment_was_carried_out_lists.json', 'TreatmentWasCarriedOutListController@treatment_was_carried_out_lists_json');
    Route::get('/region_lists.json', 'RegionListController@region_lists_json')->name('region_lists_json');
    Route::get('/cause_of_death_lists.json', 'CauseOfDeathListController@cause_of_death_lists_json')->name('cause_of_death_lists_json');
    Route::get('/patients.json', 'PatientController@patients_json')->name('patients_json');
});

Route::group(['prefix' => 'lists', 'as' => 'lists.'], function () {
    Route::get('/users.json', 'UsersController@users_json');
    Route::get('/doctors.json', 'UsersController@doctors_json');

app/Models/Cashbox.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Cashbox extends Model
{
    protected $table = 'cashboxes';
    protected $fillable = ['name','slug'];

    public function orderOutput()
    {
        return $this->hasMany(OrderOutput::class);
    }

    //orderInput
    public function orderInput()
    {
        return $this->hasMany(Order::class);
    }

}

app/Http/Controllers/CashboxController.php
<?php

namespace App\Http\Controllers;

use App\Models\AddCashbox;
use Illuminate\Http\Request;

class CashboxController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $lists = AddCashbox::all();
        return view('cashbox.index', compact('lists'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('cashbox.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->except('_token');

        AddCashbox::create($request->all());
        return redirect()->route('cashbox.index')->with('msg','ok');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = AddCashbox::find($id);
        return view('cashbox.edit',compact('item'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        AddCashbox::find($id)->update($request->all());
        return redirect()->route('cashbox.index')->with('msg','ok');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = AddCashbox::find($id);
        $item->delete();
        return redirect()->route('cashbox.index');
    }
}

resources/views/cashbox/cashboxFour/index.blade.php
@extends('layouts.cardBase')

@section('css')
    <link href="{{ mix('css/dataTables.bootstrap4.min.css') }}" rel="stylesheet" />
    <link href="{{mix("/css/jquery.magicsearch.min.css")}}" rel="stylesheet" />
@endsection

@section('card-header')
    Դրամարկղ
    <div class="card-header-actions">
        <button class="btn btn-primary float-right mr-4" type="button" data-toggle="modal"
                data-target="#order-import-modal">
            <x-svg icon="cui-plus" />
            Մուտք
        </button>
        <button class="btn btn-primary float-right mr-4" type="button" data-toggle="modal"
                data-target="#order-export-modal">
            <x-svg icon="cui-plus" />
            Ելք
        </button>

    </div>
@endsection

@section('card-content')

   @if(session('updated'))
        <div class="alert alert-success sesionDiv">
            {{session('updated')}}
        </div>
    @elseif(session('deleted'))
        <div class="alert alert-danger sesionDiv">
            {{session('deleted')}}
        </div>
    @endif

    <x-modal modal-id="order-import-modal" title="Մուտքի օրդեր" form-id="order-import-form">
        <form action="{{ route('cashbox.cashboxFour.orderinput.store') }}" id="order-import-form" method="post">
            @csrf

            <div class="alert alert-success alert-block d-none">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <strong class="alert-content"></strong>
            </div>

            <div class="form-group">
                <label>Բաժին</label>
                <x-forms.magic-search    hidden-name="departments_full_ids[]" hidden-id="department_id"
                                         placeholder="Ընտրել բաժինը․․․" class="magic-search ajax my-2" data-catalog-name="departments" />
            </div>

            <div class="form-group">
                <label>Գումարը թվերով (Դրամ)</label>

                <x-forms.text-field id="price_input"   name="price" label="" validationType="ajax" />


                {{--   <input type="number" class="form-control" type="text" name="price"  />--}}
            </div>
            <div class="form-group">
                <label>Գումարը տառերով  (Դրամ)</label>

                <x-forms.text-field id="sum_text_input" name="sum_text" label="" validationType="ajax" />
            </div>

            <div class="form-group">
                <label>Հիվանդ</label>
                <select name="patient_id" class="form-control" id="patient_id">
                    <option></option>
                    @foreach($patients as $item)
                        <option value="{{$item->id}}">{{ $item->f_name ." ".$item->l_name ." ". $item->p_name}}</option>
                    @endforeach
                </select>
            </div>


            <div class="form-group">
                <label>Նպատակ (Ծառայությանի տեսակ)</label>
                <x-forms.magic-search   hidden-name="treatment_ids[]" hidden-id="treatment_ids"
                                        placeholder="Ընտրել ծառայությունը․․․" class="magic-search ajax my-2" data-catalog-name="treatments" />
            </div>

            <div class="form-group">
                <label>Բժիշկ</label>
                <select name="user_id" class="form-control" id="user_id">
                    <option></option>
                    @foreach($doctors as $item)
                        <option value="{{$item->id}}">{{ $item->f_name ." ".$item->l_name ." ". $item->p_name}}</option>
                    @endforeach
                </select>
            </div>

            <div class="form-group">
                <label>ՀԾՀ</label>
                <x-forms.text-field type="number" id="social_card_input" name="social_card" label="" validationType="ajax" />
            </div>
            <div class="form-group">
                <label>Ստացողի անձը հաստատող փաստաթղթի անվանումը</label>
                <input name="document_type" type="text" class="form-control"  />
            </div>
            <label>Թղթակցող հաշիվ</label>
            <select name="correspondentaccount_id" class="form-control">
                <option></option>
                @foreach ($correspondentaccount as $item)
                    <option value="{{$item->id}}">{{$item->code}}</option>
                @endforeach
            </select>
        </form>
    </x-modal>

    <x-modal modal-id="order-export-modal" title="Ելքի օրդեր" form-id="order-export-form">
        <form action="{{ route('cashbox.cashboxFour.orderoutput.store')  }}" id="order-export-form" method="post">
            @csrf

            <div class="alert alert-success alert-block d-none">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <strong class="alert-content"></strong>
            </div>
            <div class="form-group">
                <label>Գումարը թվերով (Դրամ)</label>
                <input name="price" type="number" class="form-control" type="text" validationType="ajax" />
            </div>

            <div class="form-group">
                <label>Գումարը տառերով (Դրամ)</label>
                <input name="sum_text" type="text" class="form-control" type="text" validationType="ajax" />
            </div>
            <div class="form-group">
                <label>Ստացողի անձը հաստատող փաստաթղթի անվանումը</label>
                <input name="document_type" type="text" class="form-control" type="text"  />

            </div>

            <div class="form-group">
                <label>Հիվանդ</label>
                <select name="patient_id" class="form-control" id="patient_id">
                    <option></option>
                    @foreach($patients as $item)
                        <option value="{{$item->id}}">{{ $item->f_name ." ".$item->l_name ." ". $item->p_name}}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <label>ՀԾՀ</label>
                <x-forms.text-field type="number" id="social_card_input" name="social_card" label="" validationType="ajax" />
            </div>

            <label>Թղթակցող հաշիվ</label>
            <select name="cancer_group" class="form-control">
                <option></option>
                @foreach ($correspondentaccount as $item)
                    <option value="{{$item->id}}">{{$item->code}}</option>
                @endforeach
            </select>
            <div class="form-group">
                <label>Համարը, ամսաթիվը և հանձման վայրը</label>

                <textarea name="passport_data" class="form-control" id="" cols="30" rows="10"></textarea>
            </div>

        </form>
    </x-modal>

    <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="input-order-tab" data-toggle="pill" href="#input-order" role="tab" aria-controls="input-order" aria-selected="true">Ելքի օրդերներ</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="output-order-tab" data-toggle="pill" href="#output-order" role="tab" aria-controls="output-order" aria-selected="false">Մուտքի օրդերներ</a>
        </li>

    </ul>
    <div class="tab-content" id="pills-tabContent">
        <div class="tab-pane fade show active" id="input-order" role="tabpanel" aria-labelledby="input-order-tab">
            <table id="example" class="table table-striped table-bordered table-cursor" style="width: 100%;">
                <thead>
                <tr>
                    <th>N</th>
                    <th>Ամսաթիվ</th>
                    <th>Գումար</th>
                    <th>Պացիենտ</th>
                    <th>Գործողություններ</th>
                </tr>
                </thead>
                <tbody>
                @foreach($orderOutput as $order)
                    <tr data-url={{url("/cashbox/order/{$order->id}/show_1_CashInputOrders")}}>
                        <td>{{ $order->id }}</td>
                        <td>{{ $order->created_at }}</td>
                        <td>{{ $order->price }}</td>
                        <th>{{ $order->patient->f_name }}&nbsp;{{ $order->patient->l_name }}&nbsp;{{ $order->patient->p_name }}</th>
                        <th>
                            <a class="btn btn-info btn-sm" href="{{ route('cashbox.cashboxFour.orderoutput.show', $order) }}">
                                <svg class="c-icon">
                                    <use xlink:href="/assets/icons/coreui/free-symbol-defs.svg#cui-applications"></use>
                                </svg>
                            </a>
                            <a href="{{ route('cashbox.cashboxFour.orderoutput.edit',$order->id) }}" class="btn btn-primary btn-sm" >
                                <x-svg icon="cui-pencil" />
                            </a>
                            <form style="display:inline" action="{{ route('cashbox.cashboxFour.orderoutput.destroy',$order->id) }}" method="post">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger btn-sm" type="submit"><x-svg icon="cui-trash" /></button>
                            </form>
                        </th>
                    </tr>
                @endforeach

                </tbody>
            </table>
        </div>
        <div class="tab-pane fade" id="output-order" role="tabpanel" aria-labelledby="output-order-tab">
            <table id="example" class="table table-striped table-bordered table-cursor" style="width: 100%;">
                <thead>
                <tr>
                    <th>N</th>
                    <th>Ամսաթիվ</th>
                    <th>Գումար</th>
                    <th>Պացիենտ</th>
                    <th>Գործողություններ</th>
                </tr>
                </thead>
                <tbody>
                @foreach($ordersInput as $order)
                    <tr data-url={{url("/cashbox/order/{$order->id}/show_1_CashInputOrders")}}>
                        <td>{{ $order->id }}</td>
                        <td>{{ $order->created_at }}</td>
                        <td>{{ $order->price }}</td>
                        <th>{{ $order->patient->f_name }}&nbsp;{{ $order->patient->l_name }}&nbsp;{{ $order->patient->p_name }}</th>
                        <th>
                            <a class="btn btn-info btn-sm" href="{{ route('cashbox.cashboxFour.orderinput.show', $order->id) }}">
                                <svg class="c-icon">
                                    <use xlink:href="/assets/icons/coreui/free-symbol-defs.svg#cui-applications"></use>
                                </svg>
                            </a>
                            <a href="{{ route('cashbox.cashboxFour.orderinput.edit',$order->id) }}" class="btn btn-primary btn-sm" >
                                <x-svg icon="cui-pencil" />
                            </a>
                            <form style="display:inline" action="{{ route('cashbox.cashboxFour.orderinput.destroy',$order->id) }}" method="post">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger btn-sm" type="submit"><x-svg icon="cui-trash" /></button>
                            </form>
                        </th>
                    </tr>
                @endforeach

                </tbody>
            </table>
        </div>
    </div>



@endsection

@section('javascript')
    <script src="{{ mix('js/jquery.js') }}"></script>
    <script src="{{ mix('js/datatables.js') }}"></script>
    <script src="{{ mix('js/all.magicsearch.js') }}"></script>

    <script>
        $(document).ready(function() {
            const documentsDt = $("#example").CDataTable({
                rowGroup: {
                    dataSrc: 5
                }
            });
        });
    </script>
@endsection